# Generated by Django 6.0 on 2025-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
