# Generated by Django 6.0 on 2025-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='scraped_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='site',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
