# Generated by Django 6.0 on 2025-12-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_scraped_at_alter_job_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
