# Generated by Django 6.0 on 2025-12-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_match',
            field=models.FloatField(default=0),
        ),
    ]
